P############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# about
[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
parent = "About"
name = "About the IPMC"
url = "/about"

[[main]]
parent = "About"
name = "Announcements"
url = "/announcements"

[[main]]
parent = "About"
name = "Board of Directors"
url = "/about/board"

[[main]]
parent = "About"
name = "Financials"
url = "/about/financials"

[[main]]
parent = "About"
name = "Board Meeting Minutes"
url = "/about/minutes"

# assets
[[main]]
weight = 3
name = "Assets"

[[main]]
parent = "Assets"
name = "Contact"
url = "/contact"

[[main]]
parent = "Assets"
name = "Authors"
url = "/authors"

[[main]]
parent = "Assets"
name = "Categories"
url = "/categories"

[[main]]
parent = "Assets"
name = "404 Page"
url = "/404"

# documents
[[main]]
weight = 4
name = "Documents"

[[main]]
parent = "Documents"
name = "Elements"
url = "/elements"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
